### PR TITLE
Revert "Make compatible with python/pypy 3"

### PR DESCRIPTION
**Pull request by alexprengere**
Reverts alexprengere/PythonBrainFuck#1

The PR breaks the RPython compilation for me, with both Pypy and Pypy3 (worked fine on previous commit).

### CODE REVIEW

**Comment by amateurhourrrr** [comment]
Sorry I think I misunderstood the purpose of the other branch in this repo. I thought RPython was a WIP still for some reason - brainfart

I'll take a look at the RPython docs on how best to handle the IO in a portable way and if I get it working I'll submit another PR

**Comment by alexprengere** [comment]
I am not actually sure what you are trying to accomplish here. The code of `bf.py` is valid RPython code and statically compiles using either pypy or pypy3 toolchains (check the steps [here](https://alexprengere.github.io/PythonBrainFuck/)). This compilation produce binaries (with or without JIT) that can run any BF code. RPython code is also valid Python2 code, so `bf.py` can be run with any Python2 interpreter, like CPython2.7 or Pypy, but not Pypy3 since Pypy3 is a Python3 interpreter. Let me know if things are still unclear.

I deleted any other branches that were indeed outdated to avoid confusion.

**Comment by amateurhourrrr** [comment]
I was indeed aiming for pypy3 (where it worked with the PR), but where I choked significantly was in coming up with a way to run it with pypy3 _and_ pypy2 _and_ still have it work with RPython. I guess it's not worth it anyways.

Thanks for taking the time to look at this and reply to me, apologies for the dead end time waste

**Comment by alexprengere** [comment]
No problem at all, thanks for taking interest in this.

**Pull request merged**
